name: xmly_speed

on:
  workflow_dispatch:
  schedule:
    - cron: "5,35 * * * *"
  watch:
    types: [started]
  repository_dispatch:
    types: xmly_speed

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: zt6/github_sazs34_MyActions
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          pip install -r ./requirements.txt
      - name: Run Job
        run: |
          python3 xmly_speed.py
        env:
          XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}
          XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }}
          XMLY_ACCUMULATE_INDEX: ${{ secrets.XMLY_ACCUMULATE_INDEX }}
          XMLY_ACCUMULATE_HOURS: ${{ secrets.XMLY_ACCUMULATE_HOURS }}
          XMLY_ANDROID_AGENT: ${{ secrets.XMLY_ANDROID_AGENT }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          SYNCURL: https://github.com/zt6/github_Zero-S1_xmly_speed/raw/master/xmly_speed.py
